language: rust
rust:
- nightly
before_script:
  - echo DATABASE_URL=db.sqlite > .env
  - cargo install diesel_cli --no-default-features --features "sqlite-bundled" --force
  - diesel migration run
script:
- cargo build --release
cache: cargo
deploy:
  provider: heroku
  api_key: fcdf3c46-dd57-43f1-a1d7-65c742561e1c
  skip_cleanup: true
  on:
    repo: michoy/guinea-pig
